numpy -> vector 표현

In [1]:
import numpy as np

In [2]:
a = np.array([2,4])
a

array([2, 4])

In [3]:
b = np.array([1,6])
b

array([1, 6])

In [4]:
c = 4*a + (-3)*b
c

array([ 5, -2])

In [5]:
import tensorflow as tf

In [6]:
tf.__version__

'2.7.0'

In [7]:
x = tf.Variable([[1],[2],[3]])
y = tf.Variable([[4],[5],[6]])

In [12]:
xT = tf.transpose(x)
xT

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [13]:
inner_product = tf.matmul(xT, y)
inner_product

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]], dtype=int32)>

In [14]:
print(inner_product)

tf.Tensor([[32]], shape=(1, 1), dtype=int32)


In [15]:
tf.print(inner_product)

[[32]]


Norm

In [17]:
x = tf.Variable([[1],[2],[3]], dtype = tf.float32)
#xT = tf.transpose(x)
x_norm = tf.norm(x, ord = 2) # ord =2  L2 
tf.print(x_norm)

3.7416575


In [21]:
x_norm

<tf.Tensor: shape=(), dtype=float32, numpy=3.7416575>

In [20]:
x = tf.Variable([[1],[2],[3]], dtype = tf.float32)
xT = tf.transpose(x)
x_norm_2 = tf.math.sqrt(tf.matmul(xT, x))
tf.print(x_norm_2)


[[3.7416575]]


In [ ]:
# 1 by 1 mat & 1dim Vec

In [22]:
A = tf.Variable(np.array( [ [1] ]), dtype = tf.float32)
x = tf.Variable(np.array( [ [1] ]), dtype = tf.float32)
b = tf.matmul(A,x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)


(1, 1)
(1, 1)
(1, 1)
[[1]]


In [ ]:
# 1by2 mat & 2dim Vector

In [23]:
A = tf.Variable(np.array( [ [1,4]]),dtype = tf.float32)
x = tf.Variable(np.array( [ [1], [2] ]), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(1, 2)
(2, 1)
(1, 1)
[[9]]


In [25]:
A = tf.Variable(np.array( [ [1, 4], [9,5] ] ),dtype = tf.float32)
x = tf.Variable(np.array( [ [1], [2] ] ), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(2, 2)
(2, 1)
(2, 1)
[[9]
 [19]]


In [26]:
# 3 by 2 mat & 2 dim vec

In [27]:
A = tf.Variable(np.array( [ [1,4] , [9,5] , [4,0] ] ),dtype = tf.float32)
x = tf.Variable(np.array( [ [1], [2] ]), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(3, 2)
(2, 1)
(3, 1)
[[9]
 [19]
 [4]]


In [ ]:
# 4 by 3 mat & 3 dim vec

In [28]:
A = tf.Variable(np.array( [ [1,4,2],[9,5,0],[4,0,2],[6,1,8] ]  ),dtype = tf.float32)
x = tf.Variable(np.array( [ [1],[2],[3] ] ), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(4, 3)
(3, 1)
(4, 1)
[[15]
 [19]
 [10]
 [32]]


In [ ]:
# 4 by 4 mat & 4 dim Vec

In [29]:
A = tf.Variable(np.array( [[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]] ),dtype = tf.float32)
x = tf.Variable(np.array( [[1],[2],[3],[4]] ), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(4, 4)
(4, 1)
(4, 1)
[[15]
 [19]
 [26]
 [44]]


In [30]:
A = tf.Variable(np.array( [ [1,4,2,0,2],[9,5,0,0,5],[4,0,2,4,6],[6,1,8,3,1]] ),dtype = tf.float32)
x = tf.Variable(np.array( [ [1],[2],[3],[4],[5]] ), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(4, 5)
(5, 1)
(4, 1)
[[25]
 [44]
 [56]
 [49]]


In [ ]:
# 4 by 4 mat & 4 by 3 mat

In [31]:
A = tf.Variable(np.array([[1,4,2,0],
                          [9,5,0,0],
                          [4,0,2,4],
                          [6,1,8,3]]),dtype = tf.float32)
x = tf.Variable(np.array([[1,5,9],
                          [2,6,10],
                          [3,7,11],
                          [4,8,12]]), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(4, 4)
(4, 3)
(4, 3)
[[15 43 71]
 [19 75 131]
 [26 66 106]
 [44 116 188]]


In [ ]:
# 4 by 5 mat & 5 by 2 mat

In [32]:
A = tf.Variable(np.array([[1,4,2,0,2],
                          [9,5,0,0,5],
                          [4,0,2,4,6],
                          [6,1,8,3,1]]),dtype = tf.float32)
x = tf.Variable(np.array([[1,6],
                          [2,7],
                          [3,8],
                          [4,9],
                          [5,10]]), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(4, 5)
(5, 2)
(4, 2)
[[25 70]
 [44 139]
 [56 136]
 [49 144]]


In [ ]:
# 선형 시스템에 대해서 방정식 풀자~~

In [33]:
A = tf.Variable(np.array([ [1,4,0,2],
                           [9,5,0,0],
                           [4,0,2,4],
                           [6,1,8,3]] ),dtype = tf.float32)
B = tf.Variable(np.array( [ [15],
                            [19],
                            [26],
                            [44]] ),dtype = tf.float32)
x = tf.linalg.solve(A, B)
print(A.shape)
print(B.shape)
print(x.shape)
tf.print(x)

(4, 4)
(4, 1)
(4, 1)
[[1.24952018]
 [1.55086374]
 [2.95393443]
 [3.7735126]]


In [ ]:
# 위에서 푼 결과가 맞는지 검산!!!
y = tf.matmul(A, x)
tf.print(y)
print("-------")


In [ ]:
A = tf.Variable(np.array(  ),dtype = tf.float32)
x = tf.Variable(np.array(  ), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)