numpy -> vector 표현

In [14]:
import numpy as np

In [ ]:
a = np.array([2,4])
a

array([2, 4])

In [ ]:
b = np.array([1,6])
b

array([1, 6])

In [ ]:
c = 4*a + (-3)*b
c

array([ 5, -2])

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.7.0'

In [4]:
x = tf.Variable([[1],[2],[3]])
y = tf.Variable([[4],[5],[6]])

In [5]:
xT = tf.transpose(x)
xT

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [6]:
inner_product = tf.matmul(xT, y)
inner_product

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]], dtype=int32)>

In [7]:
print(inner_product)

tf.Tensor([[32]], shape=(1, 1), dtype=int32)


In [8]:
tf.print(inner_product)

[[32]]


Norm

In [9]:
x = tf.Variable([[1],[2],[3]], dtype = tf.float32)
#xT = tf.transpose(x)
x_norm = tf.norm(x, ord = 2) # ord =2  L2 
tf.print(x_norm)

3.7416575


In [10]:
x_norm

<tf.Tensor: shape=(), dtype=float32, numpy=3.7416575>

In [11]:
x = tf.Variable([[1],[2],[3]], dtype = tf.float32)
xT = tf.transpose(x)
x_norm_2 = tf.math.sqrt(tf.matmul(xT, x))
tf.print(x_norm_2)


[[3.7416575]]


In [12]:
# 1 by 1 mat & 1dim Vec

In [15]:
A = tf.Variable(np.array( [ [1] ]), dtype = tf.float32)
x = tf.Variable(np.array( [ [1] ]), dtype = tf.float32)
b = tf.matmul(A,x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)


(1, 1)
(1, 1)
(1, 1)
[[1]]


In [ ]:
# 1by2 mat & 2dim Vector

In [ ]:
A = tf.Variable(np.array( [ [1,4]]),dtype = tf.float32)
x = tf.Variable(np.array( [ [1], [2] ]), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(1, 2)
(2, 1)
(1, 1)
[[9]]


In [ ]:
A = tf.Variable(np.array( [ [1, 4], [9,5] ] ),dtype = tf.float32)
x = tf.Variable(np.array( [ [1], [2] ] ), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(2, 2)
(2, 1)
(2, 1)
[[9]
 [19]]


In [ ]:
# 3 by 2 mat & 2 dim vec

In [ ]:
A = tf.Variable(np.array( [ [1,4] , [9,5] , [4,0] ] ),dtype = tf.float32)
x = tf.Variable(np.array( [ [1], [2] ]), dtype = tf.float32)
b = tf.matmul(A, x)
print(A.shape)
print(x.shape)
print(b.shape)
tf.print(b)

(3, 2)
(2, 1)
(3, 1)
[[9]
 [19]
 [4]]
